services:
  - type: web
    name: laravel-portfolio
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_KEY
        sync: false
